extraction:
  cpp:
    configure:
      command:
        - make fetch-pb
        - cd racket/src
        - ./configure --disable-docs
    index:
      build_command:
        - cd racket/src
        - make -j2
